In [13]:
import pm4py

data = pm4py.read_xes("../../data/bpic2012/origin/BPI_Challenge_2012.xes.gz")
data

parsing log, completed traces :: 100%|██████████| 13087/13087 [00:02<00:00, 5556.43it/s]

,org:resource,lifecycle:transition,concept:name,time:timestamp,case:REG_DATE,case:concept:name,case:AMOUNT_REQ
0,112,COMPLETE,A_SUBMITTED,2011-10-01 00:38:44.546000+00:00,2011-10-01 00:38:44.546000+00:00,173688,20000
1,112,COMPLETE,A_PARTLYSUBMITTED,2011-10-01 00:38:44.880000+00:00,2011-10-01 00:38:44.546000+00:00,173688,20000
2,112,COMPLETE,A_PREACCEPTED,2011-10-01 00:39:37.906000+00:00,2011-10-01 00:38:44.546000+00:00,173688,20000
3,112,SCHEDULE,W_Completeren aanvraag,2011-10-01 00:39:38.875000+00:00,2011-10-01 00:38:44.546000+00:00,173688,20000
4,NaN,START,W_Completeren aanvraag,2011-10-01 11:36:46.437000+00:00,2011-10-01 00:38:44.546000+00:00,173688,20000
...,...,...,...,...,...,...,...
262195,112,COMPLETE,A_PARTLYSUBMITTED,2012-02-29 23:51:17.423000+00:00,2012-02-29 23:51:16.799000+00:00,214376,15000
262196,112,SCHEDULE,W_Afhandelen leads,2012-02-29 23:52:01.287000+00:00,2012-02-29 23:51:16.799000+00:00,214376,15000
262197,11169,START,W_Afhandelen leads,2012-03-01 09:26:46.736000+00:00,2012-02-29 23:51:16.799000+00:00,214376,15000
262198,11169,COMPLETE,A_DECLINED,2012-03-01 09:27:37.118000+00:00,2012-02-29 23:51:16.799000+00:00,214376,15000
262199,11169,COMPLETE,W_Afhandelen leads,2012-03-01 09:27:41.325000+00:00,2012-02-29 23:51:16.799000+00:00,214376,15000

In [14]:
data = data[["case:concept:name", "concept:name", "time:timestamp"]]

In [15]:
from pm4py.objects.log.util.sorting import sort_timestamp_log, sort_timestamp_trace

log = sort_timestamp_log(data)
print(log)
for i, trace in enumerate(log):
    # print first and last event in trace
    print(trace[0]["concept:name"], trace[0]["time:timestamp"], sep="\n")
    print(trace[-1]["concept:name"], trace[-1]["time:timestamp"], sep="\n")

    print()
    if i == 2:
        break

[{'attributes': {'concept:name': '173688'}, 'events': [{'concept:name': 'A_SUBMITTED', 'time:timestamp': Timestamp('2011-10-01 00:38:44.546000+0000', tz='UTC')}, '..', {'concept:name': 'W_Valideren aanvraag', 'time:timestamp': Timestamp('2011-10-13 10:37:37.026000+0000', tz='UTC')}]}, '....', {'attributes': {'concept:name': '214376'}, 'events': [{'concept:name': 'A_SUBMITTED', 'time:timestamp': Timestamp('2012-02-29 23:51:16.799000+0000', tz='UTC')}, '..', {'concept:name': 'W_Afhandelen leads', 'time:timestamp': Timestamp('2012-03-01 09:27:41.325000+0000', tz='UTC')}]}]
A_SUBMITTED
2011-10-01 00:38:44.546000+00:00
W_Valideren aanvraag
2011-10-13 10:37:37.026000+00:00

A_SUBMITTED
2011-10-01 08:08:58.256000+00:00
W_Valideren aanvraag
2011-10-10 14:17:34.633000+00:00

A_SUBMITTED
2011-10-01 08:10:30.287000+00:00
W_Wijzigen contractgegevens
2012-02-15 12:29:26.299000+00:00

In [16]:
log = log[1:]
for i, trace in enumerate(log):
    # print first and last event in trace
    print(trace[0]["concept:name"], trace[0]["time:timestamp"], sep="\n")
    print(trace[-1]["concept:name"], trace[-1]["time:timestamp"], sep="\n")

    print()
    if i == 2:
        break

A_SUBMITTED
2011-10-01 08:08:58.256000+00:00
W_Valideren aanvraag
2011-10-10 14:17:34.633000+00:00

A_SUBMITTED
2011-10-01 08:10:30.287000+00:00
W_Wijzigen contractgegevens
2012-02-15 12:29:26.299000+00:00

A_SUBMITTED
2011-10-01 08:11:08.866000+00:00
A_DECLINED
2011-10-01 08:11:46.420000+00:00